keys:
  - &admin age13sdd3dsa2yhm6emenlnz0zyerswwa72w0e4lxny6xk2rnxacn9xs0gfnf9
  - &aorus_nixos age1l3xewx6hfj3wsjy880nfp2jt3dszgghqu0gqkw7yaqx9hyjpmujsm3dr7w
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin
        - *aorus_nixos
