keys:
  - &admin age1mau3zgns2as905ctc466pk8r837l92jcwyl3vr87w5rte4pcwfcqvunnwl
  - &aorus_nixos age1r5j0kglpqzr60nnf3nk9dsuecp5jrjdgsx0gpy5dz4nx8455j3vqpsrsfu
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin
        - *aorus_nixos
