keys:
  - &azurblade age1lflc9368khx0pflwd4hdadwap44ysuuc8aw8mxf04zhhmmwqf9nqg9dt5t
  - &macmini_ssh age1cdzjqn9qkpw8ud6yvx8qa66623fsaj8vem72yvr3tt5nf3p23ssq883z8s
  - &macbookpro age16ahj6xx6pdsa8zfkh7ezfafy3nc64m29dn4zv063js7y0vns0ppsfrjnfs
  - &admin age1mau3zgns2as905ctc466pk8r837l92jcwyl3vr87w5rte4pcwfcqvunnwl
  - &admin_azurblade age1ncqpx03pxy5wuqzgqhe5xkyv2fx23r66q7tz8dx78un6a2pde9ssds7sqh
  - &aorus_nixos age1d5mswlth93a23h8224tsuhyahazcrstz9xu26nvh85765mk8kytstvdqsv
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *azurblade
          - *macmini_ssh
          - *macbookpro
          - *admin
          - *admin_azurblade
          - *aorus_nixos
