{
  description = "My personal flakes";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    nixos-wsl = {
      url = "github:nix-community/NixOS-WSL/main";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    eza = {
      url = "github:eza-community/eza";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.flake-utils.follows = "flake-utils";
    };

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    flake-parts = {
      url = "github:hercules-ci/flake-parts";
      inputs.nixpkgs-lib.follows = "nixpkgs";
    };

    nix-darwin = {
      url = "github:lnl7/nix-darwin";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    neovim-nightly-overlay = {
      url = "github:nix-community/neovim-nightly-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    # firefox = {
    #   url = "github:nix-community/flake-firefox-nightly";
    #   inputs.nixpkgs.follows = "nixpkgs";
    # };
    hyprland.url = "github:hyprwm/Hyprland";
    awww = {
      url = "git+https://codeberg.org/LGFae/awww";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    wayshot = {
      url = "github:waycrate/wayshot";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    # hyprsession.url = "github:joshurtree/hyprsession";
    hyprcursor-phinger = {
      url = "github:jappie3/hyprcursor-phinger";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    chromium-darwin = {
      url = "github:lrworth/chromium-bin-flake";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    paneru = {
      url = "github:karinushka/paneru";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.nix-darwin.follows = "nix-darwin";
    };
    claude-code = {
      url = "github:sadjow/claude-code-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    codex-cli = {
      url = "github:sadjow/codex-cli-nix";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.flake-utils.follows = "flake-utils";
    };
    nix-flatpak.url = "github:gmodena/nix-flatpak/?ref=latest";
    cc-statusline = {
      url = "github:AzurIce/cc-statusline";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.flake-utils.follows = "flake-utils";
    };
    kimi-code = {
      url = "github:MoonshotAI/kimi-code";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    herdr = {
      url = "github:ogulcancelik/herdr";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    notist = {
      url = "github:AzurIce/notist";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.flake-utils.follows = "flake-utils";
    };
    noctalia = {
      url = "github:noctalia-dev/noctalia-shell";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    inputs@{ self, ... }:
    let
      host-inputs = inputs // {
        user = "azurice";
        overlays = [
          inputs.claude-code.overlays.default
          inputs.codex-cli.overlays.default
        ];
      };
    in
    {

      nixosConfigurations.aorus-nixos = import ./hosts/aorus-nixos (
        host-inputs
        // {
          system = "x86_64-linux";
          mac = false;
        }
      );

      nixosConfigurations.nixos-wsl = import ./hosts/nixos-wsl (
        host-inputs
        // {
          system = "x86_64-linux";
          mac = false;
        }
      );

      nixosConfigurations.azurblade = import ./hosts/azurblade (
        host-inputs
        // {
          system = "x86_64-linux";
          mac = false;
        }
      );

      darwinConfigurations.azurmac-macos = import ./hosts/azurmac-macos (
        host-inputs
        // {
          system = "aarch64-darwin";
          mac = true;
        }
      );

      darwinConfigurations.azur-macmini = import ./hosts/azur-macmini (
        host-inputs
        // {
          system = "aarch64-darwin";
          mac = true;
        }
      );
    }
    // inputs.flake-utils.lib.eachSystem [ "x86_64-linux" "aarch64-linux" "aarch64-darwin" ] (
      system:
      let
        lib = inputs.nixpkgs.lib;
        pkgs = import inputs.nixpkgs {
          inherit system;
          config.allowUnfreePredicate = pkg: (pkg.pname or "") == "zcode";
        };
        # generated by `just update` from packages/nvfetcher.toml
        sources = import ./packages/_sources/generated.nix {
          inherit (pkgs)
            fetchgit
            fetchurl
            fetchFromGitHub
            dockerTools
            ;
        };
        # mlx-bin = pkgs.python3Packages.callPackage ./packages/mlx-bin.nix { };
        # mlx-audio = pkgs.python3Packages.callPackage ./packages/mlx-audio.nix {
        #   # use the official wheel (with Metal support) instead of nixpkgs'
        #   # CPU-only source build
        #   mlx = mlx-bin;
        # };
      in
      {
        packages = {
          cc-switch = import ./packages/cc-switch.nix {
            inherit lib sources;
            inherit (pkgs) stdenvNoCC unzip;
          };
          splitrail = import ./packages/splitrail.nix {
            inherit lib sources;
            inherit (pkgs) stdenvNoCC unzip;
          };
          revelo = import ./packages/revelo.nix {
            inherit lib sources;
            inherit (pkgs) stdenvNoCC;
          };
          clipvault = import ./packages/clipvault.nix {
            inherit lib sources;
            inherit (pkgs) stdenv autoPatchelfHook gcc;
          };
          dsh = import ./packages/dsh.nix {
            inherit lib sources;
            inherit (pkgs) stdenv buildNpmPackage nodejs_24 python3 jq;
          };
          opencode = import ./packages/opencode.nix {
            inherit lib sources;
            inherit (pkgs) stdenvNoCC unzip makeWrapper glibc;
          };
          # mlx-audio = mlx-audio;
          # mlx-vlm = pkgs.python3Packages.callPackage ./packages/mlx-vlm.nix {
          #   inherit mlx-audio;
          #   mlx = mlx-bin;
          # };
        }
        // (if pkgs.stdenv.hostPlatform.isLinux then {
          zcode = import ./packages/zcode.nix {
            inherit lib;
            inherit (pkgs) appimageTools fetchurl;
          };
        } else { });

        devShells.default = pkgs.mkShell {
          packages = with pkgs; [
            nh
            sops
            ssh-to-age
            age
            # for `just update` / `just update-dsh`
            nvfetcher
            nodejs_24
            prefetch-npm-deps
          ];
        };
      }
    );
}
