# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

let
  uuid = "22edbf0b-9105-4fb5-a378-905825f76f72";
  persistFs = path: {
    device = "/persist${path}";
    neededForBoot = true;
    fsType = "none";
    options = [ "bind" ];
  };
  btrSubvolFs = subvol: {
    device = "/dev/disk/by-uuid/${uuid}";
    fsType = "btrfs";
    options = [ "subvol=${subvol}" ];
  };
  persistBind = baseDir: path: {
    name = "${if baseDir == "/" then "" else baseDir}${path}";
    value = persistFs path;
  };
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];
  boot.kernelPackages = pkgs.linuxKernel.packages.linux_7_2;

  fileSystems = {
    "/boot" = {
      device = "/dev/disk/by-uuid/A57D-C07F";
      fsType = "vfat";
      options = [
        "fmask=0022"
        "dmask=0022"
      ];
    };

    "/" = btrSubvolFs "@root";
    # /nix 已迁至 GM7000 盘尾的 200G 独立分区（NixStore），sda3 上旧 @nix 已弃用
    "/nix" = {
      device = "/dev/disk/by-uuid/af9cf058-4b2b-4ca6-b08a-2dc006d1e9bd";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" ];
    };
    "/home" = btrSubvolFs "@home" // {
      neededForBoot = true;
    }; # For ~/.age-key.txt to make sops-nix set password
    "/persist" = (btrSubvolFs "@persist") // {
      neededForBoot = true;
    };
    "/home/azurice/Files" = {
      device = "/dev/disk/by-uuid/ccca6d60-ebf5-4023-8273-017d67efb4f4";
      fsType = "btrfs";
      options = [ "compress=zstd" ];
    };
    # Windows 游戏盘 _Game_（nvme2n1p4，NTFS，UUID 464606A6460696B9），开机自动挂到 ~/Games。
    # 选项说明：uid/gid 让文件归 azurice:users；iocharset=utf8 解决中文文件名乱码；
    # prealloc 预分配；nofail 保证盘不在时也能正常开机（挂载点会是空目录）。
    "/home/azurice/Games" = {
      device = "/dev/disk/by-uuid/464606A6460696B9";
      fsType = "ntfs3";
      options = [
        "uid=1000"
        "gid=100"
        "iocharset=utf8"
        "prealloc"
        "nofail"
      ];
    };
    # "/gaming" = {
    #   device = "/dev/nvme0n1p5";
    #   fsType = "ntfs";
    #   options = [ "rw" "uid=1000" "gid=100" "user" "exec" "umask=000" ];
    # };
  }
  // builtins.listToAttrs [
    (persistBind "/" "/var/log")
    (persistBind "/" "/etc/nixos")
    # (persistBind "/etc/ssh" "/ssh")
    # These will cause empty ssh file while ssh file is not exist in persist
    # (persistBind "/etc" "/ssh/ssh_host_ed25519_key")
    # (persistBind "/etc" "/ssh/ssh_host_ed25519_key.pub")
    # (persistBind "/etc" "/ssh/ssh_host_rsa_key")
    # (persistBind "/etc" "/ssh/ssh_host_rsa_key.pub")
  ];
  services.openssh.hostKeys = [
    {
      path = "/persist/etc/ssh/ssh_host_ed25519_key";
      type = "ed25519";
    }
    {
      path = "/persist/etc/ssh/ssh_host_rsa_key";
      type = "rsa";
      bits = 4096;
    }
  ];

  swapDevices = [ { device = "/dev/disk/by-uuid/cfebcefc-f250-4b15-ba48-eecdb3ef6d86"; } ];
  # 休眠（swap 同上）：写入 initrd 内核参数 resume=，initrd 里 systemd-hibernate-resume
  # 会在挂载根文件系统之前恢复内存镜像，Wayland 会话原样回来
  boot.resumeDevice = "/dev/disk/by-uuid/cfebcefc-f250-4b15-ba48-eecdb3ef6d86";
  # zramSwap.enable = true;
  boot.zswap.enable = true;

  boot.initrd.systemd = {
    extraBin = {
      btrfs = "${pkgs.btrfs-progs}/bin/btrfs";
      find = "${pkgs.findutils}/bin/find";
    };
    services.btrfs-root-reset = {
      description = "Archive old BTRFS root subvolume and create a fresh one";
      wantedBy = [ "initrd.target" ];
      before = [ "sysroot.mount" ];
      # 必须排在 hibernate resume 之后：恢复成功时 initrd 被挂起的内核直接接管，
      # 本服务不会运行；若和 resume 并行先删了 @root，恢复中的内核会写坏文件系统。
      # 冷启动（无休眠镜像）时 resume 失败退出，本服务照常执行。
      after = [ "initrd-root-device.target" "systemd-hibernate-resume.service" ];
      requires = [ "initrd-root-device.target" ];
      unitConfig.DefaultDependencies = "no";
      serviceConfig.Type = "oneshot";
      script = ''
        set -euo pipefail
        export LC_ALL=C
        mountpoint=/btrfs_tmp
        keep_roots=3
        archive_list=

        mkdir -p "$mountpoint"
        # 子卷路径相对于 Btrfs 顶层，不能依赖默认子卷仍然是 ID 5。
        mount -o subvolid=5 /dev/disk/by-uuid/${uuid} "$mountpoint"
        cleanup() {
          if [[ -n "$archive_list" ]]; then
            rm -f -- "$archive_list"
          fi
          umount "$mountpoint"
        }
        trap cleanup EXIT

        mkdir -p "$mountpoint/old_roots"
        if [[ -e "$mountpoint/@root" ]]; then
          # 用当前归档时间命名；纳秒避免同一秒内重试时撞名。
          timestamp=$(date -u +%Y-%m-%d_%H-%M-%S.%N)
          archived_root="$mountpoint/old_roots/$timestamp"
          mv -T -- "$mountpoint/@root" "$archived_root"
          # 保留策略按归档时间排序，不使用旧根目录最后被修改的时间。
          touch -- "$archived_root"
        fi

        prune_old_roots() {
          local entry old_root count=0
          if ! archive_list=$(mktemp /run/btrfs-old-roots.XXXXXX); then
            echo "WARNING: cannot list old roots; skipping cleanup" >&2
            return 0
          fi
          # 只选直接目录；NUL 分隔保留路径中的空格、换行等字符。
          if ! find "$mountpoint/old_roots" -mindepth 1 -maxdepth 1 -type d \
            -printf '%T@ %p\0' | sort -z -nr > "$archive_list"; then
            echo "WARNING: cannot sort old roots; skipping cleanup" >&2
            return 0
          fi
          while IFS= read -r -d "" entry; do
            old_root="''${entry#* }"
            # 普通目录和符号链接不能作为清理目标，也不计入保留数量。
            if ! btrfs subvolume show "$old_root" > /dev/null; then
              echo "WARNING: skipping non-subvolume: $old_root" >&2
              continue
            fi
            count=$((count + 1))
            if (( count > keep_roots )); then
              # 工具负责先删嵌套子卷；普通文件无需逐个 rm。
              if ! btrfs subvolume delete --recursive "$old_root"; then
                echo "WARNING: failed to delete old root: $old_root" >&2
              fi
            fi
          done < "$archive_list"
        }

        # 旧根清理失败可继续启动；挂载、归档和新建根失败必须报错。
        prune_old_roots
        btrfs subvolume create "$mountpoint/@root"
      '';
    };
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
