# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  clipvault-aarch64-linux = {
    pname = "clipvault-aarch64-linux";
    version = "1.3.0";
    src = fetchurl {
      url = "https://github.com/rolv-apneseth/clipvault/releases/download/v1.3.0/clipvault-aarch64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-KL+Ip0Lrz052m4gmRiWgD00ErO1r+2Oxa8+zS2S8ek0=";
    };
  };
  clipvault-x86_64-linux = {
    pname = "clipvault-x86_64-linux";
    version = "1.3.0";
    src = fetchurl {
      url = "https://github.com/rolv-apneseth/clipvault/releases/download/v1.3.0/clipvault-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-0XQWsdBQ/z+MnVKqhnRsRPVWLuVL47iD3izAUrZLCo8=";
    };
  };
  dsh = {
    pname = "dsh";
    version = "0.2.0-rc.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/@deepseek-ai/dsh/-/dsh-0.2.0-rc.2.tgz";
      sha256 = "sha256-vSeEfERc1opWWsH5HAa7vMdjnvkwcfZ4u1nF66/ziFk=";
    };
  };
  opencode-aarch64-darwin = {
    pname = "opencode-aarch64-darwin";
    version = "1.18.34";
    src = fetchurl {
      url = "https://github.com/anomalyco/opencode/releases/download/v1.18.34/opencode-darwin-arm64.zip";
      sha256 = "sha256-hSK3D1RRhLOo2XxcpPgUCTskdtcq6/2oxIvNBy7DHRs=";
    };
  };
  opencode-aarch64-linux = {
    pname = "opencode-aarch64-linux";
    version = "1.18.34";
    src = fetchurl {
      url = "https://github.com/anomalyco/opencode/releases/download/v1.18.34/opencode-linux-arm64.tar.gz";
      sha256 = "sha256-u9s/AMLFHkLjFVJSMxUTCXJCJqh3bajpFF47D6PVMQ8=";
    };
  };
  opencode-x86_64-darwin = {
    pname = "opencode-x86_64-darwin";
    version = "1.18.34";
    src = fetchurl {
      url = "https://github.com/anomalyco/opencode/releases/download/v1.18.34/opencode-darwin-x64.zip";
      sha256 = "sha256-Zr8GOM/607Zb1mSMw5R2GeHdcfS/7uCoHgh6wDa7EIg=";
    };
  };
  opencode-x86_64-linux = {
    pname = "opencode-x86_64-linux";
    version = "1.18.34";
    src = fetchurl {
      url = "https://github.com/anomalyco/opencode/releases/download/v1.18.34/opencode-linux-x64.tar.gz";
      sha256 = "sha256-DyJHlkcibR0t2ZWV0gCC7nvaOHC2LcapC0Hvwacdfpo=";
    };
  };
  pi-aarch64-darwin = {
    pname = "pi-aarch64-darwin";
    version = "1.0.3";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v1.0.3/pi-darwin-arm64.tar.gz";
      sha256 = "sha256-exqom6E1QvGsph69Y0htBBe10v79XEHt7djQg6txmyM=";
    };
  };
  pi-aarch64-linux = {
    pname = "pi-aarch64-linux";
    version = "1.0.3";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v1.0.3/pi-linux-arm64.tar.gz";
      sha256 = "sha256-0wk6eayeIu9DDipz4AKj3etFHeB7cis6pTqmqU6qntw=";
    };
  };
  pi-x86_64-darwin = {
    pname = "pi-x86_64-darwin";
    version = "1.0.3";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v1.0.3/pi-darwin-x64.tar.gz";
      sha256 = "sha256-dp4MHVmdvI5jrDVZV77I6YMr/5HxkNZ0MjkuYqxVIZQ=";
    };
  };
  pi-x86_64-linux = {
    pname = "pi-x86_64-linux";
    version = "1.0.3";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v1.0.3/pi-linux-x64.tar.gz";
      sha256 = "sha256-m4x/9SO9kIgdHBUFFo8LnessA1c5a5K2L3mVUKSP8e0=";
    };
  };
  splitrail-aarch64-darwin = {
    pname = "splitrail-aarch64-darwin";
    version = "3.10.3";
    src = fetchurl {
      url = "https://github.com/Piebald-AI/splitrail/releases/download/v3.10.3/splitrail-v3.10.3-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-s9KEIN4vcSTker4ocpW41FaEtzhm9A66dLGo+tk43HQ=";
    };
  };
  splitrail-aarch64-linux = {
    pname = "splitrail-aarch64-linux";
    version = "3.10.3";
    src = fetchurl {
      url = "https://github.com/Piebald-AI/splitrail/releases/download/v3.10.3/splitrail-v3.10.3-aarch64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-e5wWzmmflLjFpn7CSytvmSZJQ3Bx5B7S41VwmA5XFA4=";
    };
  };
  splitrail-x86_64-darwin = {
    pname = "splitrail-x86_64-darwin";
    version = "3.10.3";
    src = fetchurl {
      url = "https://github.com/Piebald-AI/splitrail/releases/download/v3.10.3/splitrail-v3.10.3-x86_64-apple-darwin.tar.gz";
      sha256 = "sha256-Ki0ztiBrWLkuFkIGLAAYjC4oxKARBrQ7aqrEH6mvmlA=";
    };
  };
  splitrail-x86_64-linux = {
    pname = "splitrail-x86_64-linux";
    version = "3.10.3";
    src = fetchurl {
      url = "https://github.com/Piebald-AI/splitrail/releases/download/v3.10.3/splitrail-v3.10.3-x86_64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-RaBnQ9D0DAMn648KKc7XTkf39hQsvIO6uBR8GNcMGQ0=";
    };
  };
  step-code-aarch64-linux = {
    pname = "step-code-aarch64-linux";
    version = "0.1.2";
    src = fetchurl {
      url = "https://static-openapi.stepfun.com/stepcode/0.1.2/step-0.1.2-linux-arm64.tar.gz";
      sha256 = "sha256-Y21VFTKBWYprFz9ZkACUciSa3ZnN6XsBX4TWWES6Dac=";
    };
  };
  step-code-x86_64-linux = {
    pname = "step-code-x86_64-linux";
    version = "0.1.2";
    src = fetchurl {
      url = "https://static-openapi.stepfun.com/stepcode/0.1.2/step-0.1.2-linux-x64.tar.gz";
      sha256 = "sha256-6XYFqMSLiAhyRjeyoMmT4/8QD7SEfoNYI2MSZPmU0Xc=";
    };
  };
}
