# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cc-switch = {
    pname = "cc-switch";
    version = "3.20.2";
    src = fetchurl {
      url = "https://github.com/farion1231/cc-switch/releases/download/v3.20.2/CC-Switch-v3.20.2-macOS.zip";
      sha256 = "sha256-CXKtzlE/B9ekL4VLgtZ3avtLOCTHCVk+j+aDZ6Kdgew=";
    };
  };
  clipvault-aarch64-linux = {
    pname = "clipvault-aarch64-linux";
    version = "1.3.0";
    src = fetchurl {
      url = "https://github.com/rolv-apneseth/clipvault/releases/download/v1.3.0/clipvault-aarch64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-KL+Ip0Lrz052m4gmRiWgD00ErO1r+2Oxa8+zS2S8ek0=";
    };
  };
  clipvault-x86_64-linux = {
    pname = "clipvault-x86_64-linux";
    version = "1.3.0";
    src = fetchurl {
      url = "https://github.com/rolv-apneseth/clipvault/releases/download/v1.3.0/clipvault-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-0XQWsdBQ/z+MnVKqhnRsRPVWLuVL47iD3izAUrZLCo8=";
    };
  };
  codex-app-x86_64-linux = {
    pname = "codex-app-x86_64-linux";
    version = "26.908.40834";
    src = fetchurl {
      url = "https://persistent.oaistatic.com/codex-app-prod/linux/deb/latest/chatgpt_amd64.deb";
      sha256 = "sha256-2je457zvquoBnEeMrL5sc+4d3RXg4euzx+8KQt2BisI=";
    };
  };
  dsh = {
    pname = "dsh";
    version = "0.1.5-rc.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/@deepseek-ai/dsh/-/dsh-0.1.5-rc.1.tgz";
      sha256 = "sha256-Gnlxnxx2ORisMOgZTfeDqTMMaxLV8EyVBzGj+KHD2dA=";
    };
  };
  opencode-aarch64-darwin = {
    pname = "opencode-aarch64-darwin";
    version = "1.18.30";
    src = fetchurl {
      url = "https://github.com/anomalyco/opencode/releases/download/v1.18.30/opencode-darwin-arm64.zip";
      sha256 = "sha256-peQ9aIc4bvx9aM5Jrijju9/e49/R1xabYSw85n5Tseg=";
    };
  };
  opencode-aarch64-linux = {
    pname = "opencode-aarch64-linux";
    version = "1.18.30";
    src = fetchurl {
      url = "https://github.com/anomalyco/opencode/releases/download/v1.18.30/opencode-linux-arm64.tar.gz";
      sha256 = "sha256-QRGlXCoCwPrDFL1R6aIzAoDm0p0rhblVT/9tYmElZu0=";
    };
  };
  opencode-x86_64-darwin = {
    pname = "opencode-x86_64-darwin";
    version = "1.18.30";
    src = fetchurl {
      url = "https://github.com/anomalyco/opencode/releases/download/v1.18.30/opencode-darwin-x64.zip";
      sha256 = "sha256-dFMAflj/EiQBQ42VzLJDNIdLWQjcrud4g/lsIzldVxA=";
    };
  };
  opencode-x86_64-linux = {
    pname = "opencode-x86_64-linux";
    version = "1.18.30";
    src = fetchurl {
      url = "https://github.com/anomalyco/opencode/releases/download/v1.18.30/opencode-linux-x64.tar.gz";
      sha256 = "sha256-VQByRoWBZUlv+FuhwrZI90IejiATv0GJpoDJ/45pnRc=";
    };
  };
  revelo = {
    pname = "revelo";
    version = "0.5.6";
    src = fetchurl {
      url = "https://github.com/vbasky/revelo/releases/download/v0.5.6/revelo-v0.5.6-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-mHw/JmWYO082scTNSiGOC67H78CCQpuLkhJaGpzb/0I=";
    };
  };
  splitrail-aarch64-darwin = {
    pname = "splitrail-aarch64-darwin";
    version = "3.9.1";
    src = fetchurl {
      url = "https://github.com/Piebald-AI/splitrail/releases/download/v3.9.1/splitrail-v3.9.1-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-2+5wm4Da5m7xEU+OT/6z4RyR27EKpPEF2teLRFLD/wo=";
    };
  };
  splitrail-aarch64-linux = {
    pname = "splitrail-aarch64-linux";
    version = "3.9.1";
    src = fetchurl {
      url = "https://github.com/Piebald-AI/splitrail/releases/download/v3.9.1/splitrail-v3.9.1-aarch64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-ND2nnfT3+ipNhtoTleVdU1v/cPWa2vl+JL9aNJo9H5Y=";
    };
  };
  splitrail-x86_64-darwin = {
    pname = "splitrail-x86_64-darwin";
    version = "3.9.1";
    src = fetchurl {
      url = "https://github.com/Piebald-AI/splitrail/releases/download/v3.9.1/splitrail-v3.9.1-x86_64-apple-darwin.tar.gz";
      sha256 = "sha256-ta3lVJS5k2KI5PaWwtNJoX/qG183df2LaHSSul+gNMI=";
    };
  };
  splitrail-x86_64-linux = {
    pname = "splitrail-x86_64-linux";
    version = "3.9.1";
    src = fetchurl {
      url = "https://github.com/Piebald-AI/splitrail/releases/download/v3.9.1/splitrail-v3.9.1-x86_64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-OR8oNwLersnYGwofLs5oaVMpLtv4guPDBDCLCIjKOLw=";
    };
  };
}
